services:
  # FastAPI Backend Service
  - type: web
    name: binger-backend
    env: python
    region: oregon  # or singapore for Asia
    plan: free  # Change to 'starter' for $7/month (no cold starts)
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_production.py"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Database URL (auto-set from database service below)
      - key: DATABASE_URL
        fromDatabase:
          name: binger-db
          property: connectionString
      
      - key: IS_PRODUCTION
        value: true
      
      # These need to be added manually in Render dashboard
      # (marked as sync: false means not stored in this file)
      - key: GOOGLE_CLIENT_ID
        sync: false
      
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      - key: JWT_SECRET_KEY
        sync: false
      
      - key: OPENAI_API_KEY
        sync: false
      
      - key: GEMINI_API_KEY
        sync: false
      
      - key: GOOGLE_CUSTOM_SEARCH_API_KEY
        value: AIzaSyBB6CdVPhjexHFDdv0DYPb_nGxZ2_KLyp8
      
      - key: GOOGLE_CUSTOM_SEARCH_ENGINE_ID
        value: a61503665501e4d59
      
      - key: JWT_ALGORITHM
        value: HS256
      
      - key: JWT_ACCESS_TOKEN_EXPIRE_HOURS
        value: 24
      
      - key: CORS_ORIGINS
        value: "*"
      
      - key: DEBUG
        value: false
    
    # Health check
    healthCheckPath: /Binger/health
    
    # Auto-deploy settings
    autoDeploy: true  # Auto-deploy when you push to main branch

# PostgreSQL Database
databases:
  - name: binger-db
    databaseName: binger
    user: binger_user
    # Using default paid plan (new flexible pricing)

