services:
  - type: web
    name: binger-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_production.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

